name: JS Secret Scan

on:
  push:
    paths:
      - 'domain.txt'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go (for waybackurls)
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: |
        go install github.com/tomnomnom/waybackurls@latest
        git clone https://github.com/m4ll0k/SecretFinder.git secretfinder
        pip install -r secretfinder/requirements.txt

    - name: Run waybackurls and SecretFinder
      run: |
        mkdir -p results

        while IFS= read -r domain; do
          echo "[*] Processing $domain"
          waybackurls "$domain" | grep '\.js$' | sort -u > "results/${domain}_js_urls.txt"

          while IFS= read -r jsurl; do
            echo "[*] Scanning $jsurl"
            python3 secretfinder/SecretFinder.py -i "$jsurl" -o cli
          done < "results/${domain}_js_urls.txt"

        done < domain.txt
